const MainGridPosts = [
    {
        id: 1,
        bgColor: 'blue',
        width: 4,
        height: 4,
        content: 'Ciao',
        img: '/dummies/main-grid/dummy_1.jpg',
    },
    {
        id: 2,
        bgColor: 'red',
        width: 5,
        height: 2,
        content: 'Ciao 2',
        img: '/dummies/main-grid/dummy_2.jpg',
    },
    {
        id: 3,
        bgColor: 'yellow',
        width: 3,
        height: 2,
        content: 'Ciao 3',
        img: '/dummies/main-grid/dummy_3.jpg',
    },
    {
        id: 4,
        bgColor: 'green',
        width: 6,
        height: 2,
        content: 'Ciao 4',
        img: '/dummies/main-grid/dummy_4.jpg',
    },
    {
        id: 5,
        bgColor: 'pink',
        width: 2,
        height: 2,
        content: 'Ciao 5',
        img: '/dummies/main-grid/dummy_5.jpg',
    },
    {
        id: 6,
        bgColor: 'pink',
        width: 3,
        height: 3,
        content: 'Ciao 5',
        img: '/dummies/main-grid/dummy_6.jpg',
    },
    {
        id: 7,
        bgColor: 'pink',
        width: 6,
        height: 3,
        content: 'Ciao 5',
        img: '/dummies/main-grid/dummy_7.jpg',
    },
    {
        id: 8,
        bgColor: 'pink',
        width: 3,
        height: 3,
        content: 'Ciao 5',
        img: '/dummies/main-grid/dummy_8.jpg',
    },
]

export default MainGridPosts
